### PR TITLE
Upgrade to rp-pico 0.7.0

### PR DESCRIPTION
**Pull request by jannic**
Only compile-tested, as my desk is currently to messy to plug the neotron together without risking short circuits. :zap:

### CODE REVIEW

**Comment by thejpster** [comment]
I can test this on Saturday unless someone beats me to it.

**Comment by thejpster** [comment]
@jannic i can recommend a plastic kitchen chopping board. Easy to drill and screw standoffs into, cheap, and has integrated carrying handle.

**Comment by jannic** [comment]
Cleaned up a corner of my desk. Neotron still boots with rp-pico 0.7.0, vga output works without obvious glitches. Anything else I should try?

**Comment by thejpster** [comment]
Typing? Did the BMC go beep?

**Comment by jannic** [comment]
Typing works. No idea about sound, need to find a speaker first.

**Comment by jannic** [comment]
No need to find a proper speaker, some headphones and jumper wires are enough. Startup sound is working.

**Comment by thejpster** [comment]
Cool. That means SPI is all pointing the right way. Ship it.

**Pull request merged**
